return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "2021.03.23",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 8,
  height = 12,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 14,
  nextobjectid = 458,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "fg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 173,
          name = "player1",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 48,
          width = 5.80392,
          height = 5.80392,
          rotation = 180,
          visible = true,
          properties = {}
        },
        {
          id = 326,
          name = "mutant",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 296,
          width = 5.80392,
          height = 5.80392,
          rotation = -180,
          visible = true,
          properties = {}
        },
        {
          id = 327,
          name = "the_boss",
          type = "",
          shape = "rectangle",
          x = 226,
          y = 298,
          width = 5.80392,
          height = 5.80392,
          rotation = -90,
          visible = true,
          properties = {}
        },
        {
          id = 333,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 172,
          y = 115,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 391,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 232,
          y = 194,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 392,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 205,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 393,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 78,
          y = 116,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 394,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 272,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 395,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 201,
          y = 339,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 396,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 106,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 397,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 47,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 398,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 217,
          y = 79,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 399,
          name = "prisonner",
          type = "",
          shape = "rectangle",
          x = 38,
          y = 269,
          width = 5.80392,
          height = 5.80392,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 425,
          name = "mutant",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 280,
          width = 5.80392,
          height = 5.80392,
          rotation = -180,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 11,
      name = "mg",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 164,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 64,
          width = 24,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 64,
          width = 48,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 30,
          y = 81,
          width = 33,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 207,
          y = 227,
          width = 32,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 42,
          y = 144,
          width = 60,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 19,
          y = 240,
          width = 62,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 336,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 312,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 288,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 264,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 240,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 216,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 168,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 144,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 191,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 120,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 192,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 96,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 193,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 72,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 194,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 48,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 195,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 24,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 196,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 215,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 336,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 216,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 312,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 217,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 288,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 218,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 264,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 219,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 240,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 220,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 216,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 221,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 192,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 222,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 168,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 223,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 144,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 224,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 120,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 225,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 96,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 226,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 72,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 227,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 48,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 228,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 24,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 231,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 232,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 233,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 234,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 235,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 236,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 237,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 238,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 360,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 239,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 360,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 244,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 245,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 246,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 247,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 248,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 249,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 250,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 251,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 252,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 0,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 253,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 0,
          width = 16,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 264,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 240,
          width = 24,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 265,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 186,
          y = 261,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 340,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 130,
          y = 202,
          width = 50,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 341,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 56,
          y = 32,
          width = 44,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 343,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 75,
          width = 9,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 344,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 360,
          width = 32,
          height = 1.58579,
          rotation = -45,
          visible = true,
          properties = {}
        },
        {
          id = 345,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 40,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 346,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 66,
          y = 56,
          width = 18,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 387,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 312,
          width = 88,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 388,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 328,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 389,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 390,
          name = "",
          type = "",
          shape = "ellipse",
          x = 39,
          y = 58,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 404,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 134,
          y = 76,
          width = 6,
          height = 36,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 405,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 140,
          y = 104,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 406,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 146,
          y = 102,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 407,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 100,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 408,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 158,
          y = 98,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 409,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 42,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 410,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 44,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 411,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 46,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 412,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 48,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 413,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 50,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 414,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 52,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 415,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 54,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 416,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 56,
          width = 2,
          height = 2,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 417,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 418,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 272,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 419,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 288,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 420,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 304,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 421,
          name = "building02",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 296,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 422,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 256,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 423,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 202,
          y = 261,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 424,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 218,
          y = 261,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 426,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 427,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 208,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 428,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 192,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 429,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 184,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 430,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 136,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 431,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 136,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 432,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 203,
          y = 152,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 433,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 190,
          y = 177,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 434,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 179,
          y = 190,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 435,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 198,
          y = 165,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 436,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 227,
          width = 32,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 437,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 224,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 438,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 218,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 439,
          name = "wall02",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 221,
          width = 3,
          height = 3,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 440,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 176,
          width = 5,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 441,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 182,
          width = 5,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 442,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 188,
          width = 5,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 443,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 194,
          width = 5,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 444,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 200,
          width = 5,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 445,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 206,
          width = 5,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 446,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 173,
          y = 273,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 447,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 158,
          y = 287,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 448,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 174,
          y = 347,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 449,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 174,
          y = 329,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 450,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 46,
          y = 345,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 451,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 25,
          y = 324,
          width = 6,
          height = 6,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 452,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 100,
          y = 32,
          width = 44,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 453,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 63,
          y = 81,
          width = 31,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 454,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 102,
          y = 144,
          width = 60,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 455,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 202,
          width = 46,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 456,
          name = "building01",
          type = "",
          shape = "rectangle",
          x = 81,
          y = 240,
          width = 63,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 457,
          name = "obj1",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "bg",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 161,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 347,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 0,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 363,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 0,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 364,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 128,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 365,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 64,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 366,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 224,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 367,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 224,
          width = 96,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 368,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 96,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 369,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 96,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 370,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 224,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 371,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 288,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 372,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 373,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 320,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 374,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 160,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 375,
          name = "groundB",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 64,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 376,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 377,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 378,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 379,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 380,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 381,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 382,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 383,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 384,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 385,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 352,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 386,
          name = "groundA",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
