return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "2021.03.23",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 128,
  height = 16,
  tilewidth = 8,
  tileheight = 8,
  nextlayerid = 21,
  nextobjectid = 551,
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "BG_C",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 20,
      name = "BG_B",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 19,
      name = "BG_A",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 543,
          name = "deco01",
          type = "",
          shape = "rectangle",
          x = 16,
          y = 32,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 544,
          name = "deco01",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 80,
          width = 8,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 545,
          name = "deco01",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 80,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 546,
          name = "deco01",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 48,
          width = 24,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "MG",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 478,
          name = "skybox",
          type = "",
          shape = "ellipse",
          x = 0,
          y = -448,
          width = 1024,
          height = 1024,
          rotation = 0,
          visible = false,
          properties = {}
        },
        {
          id = 496,
          name = "player1",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 493,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 1024,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 494,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 112,
          width = 1024,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 495,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 8,
          width = 136,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 497,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 498,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 48,
          y = 16,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 499,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 72,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 500,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 88,
          y = 16,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 501,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 502,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 16,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 503,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 505,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 64,
          width = 136,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 506,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 24,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 507,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 40,
          y = 56,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 508,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 509,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 80,
          y = 56,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 510,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 104,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 511,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 56,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 512,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 144,
          y = 56,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 513,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 16,
          width = 136,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 514,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 168,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 515,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 24,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 516,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 517,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 24,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 518,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 248,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 519,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 264,
          y = 24,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 520,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 521,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 72,
          width = 136,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 522,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 523,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 64,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 524,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 200,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 525,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 64,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 526,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 527,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 64,
          width = 16,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 528,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 64,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 529,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 24,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 530,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 48,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 531,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 72,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 532,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 96,
          width = 48,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 533,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 8,
          width = 8,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 534,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 72,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 535,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 56,
          width = 8,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 536,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 376,
          y = 32,
          width = 192,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 537,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 424,
          y = 56,
          width = 192,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 538,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 368,
          y = 96,
          width = 192,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 539,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 456,
          y = 80,
          width = 192,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 540,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 24,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 541,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 688,
          y = 72,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 542,
          name = "wall01",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 48,
          width = 24,
          height = 24,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 547,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 152,
          y = 24,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 548,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 32,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 549,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 184,
          y = 40,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 550,
          name = "nme01",
          type = "",
          shape = "rectangle",
          x = 216,
          y = 48,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 18,
      name = "FG",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    }
  }
}
